// All mock data arrays have been removed as the app now uses Firebase Realtime Database.
// In a real-world scenario, this analytics data would be generated by a backend service
// or Cloud Functions that aggregate data from the database.

export const mockAnalyticsData = {
    totalUsers: 1250,
    totalCourses: 15,
    totalVideos: 250,
    totalPDFs: 80,
    watchTimeData: [
        { name: 'Jan', hours: 400 }, { name: 'Feb', hours: 300 }, { name: 'Mar', hours: 600 },
        { name: 'Apr', hours: 800 }, { name: 'May', hours: 500 }, { name: 'Jun', hours: 700 }
    ],
    courseCompletionData: [
        { name: 'React', completion: 75 }, { name: 'Node.js', completion: 60 },
        { name: 'UI/UX', completion: 85 }, { name: 'DevOps', completion: 40 }
    ]
};
